substitutions:
  name: flower
  fname: Flower
  manufacture: Kusheev Sergei
  device_description: "Flower systeme"
  version: 1.0.0

esp32:
  board: esp32dev
#  board: esp32-c3-devkitm-1
  framework:
    type: arduino

esphome:
  name: ${name}
  friendly_name: ${fname}
  comment: ${device_description}
  project:
    name: "immortalserg.flover"
    version: ${version}

logger:
  level: INFO
api:
  reboot_timeout: 0s
ota:
  - platform: esphome
    password: "b69751c0c1385709addd896571fc010e"
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Flower"
    password: "123456789"
captive_portal:

web_server:
  port: 80
  local: True  
  version: 3


packages:
  - !include flower/global.yaml
  - !include flower/lng_rus.yaml
  - !include flower/sensor.yaml
  - !include flower/flower_sensor.yaml     # датчики влажности почвы 1 - 4
#  - !include flower/flower_sensor2.yaml    # датчики влажности почвы 5 - 8
  - !include flower/pump_gpio.yaml         # насосы 1 - 4 подключенные к GPIO
#  - !include flower/pump_gpio2.yaml        # насосы 5 - 8 подключенные к GPIO
  - !include flower/schedule.yaml          # планировщик полива 1 - 4
#  - !include flower/schedule2.yaml         # планировщик полива 5 - 8
  - !include flower/i2c.yaml               # инициализация шины i2c
#  - !include flower/pump_pcf8574.yaml      # насосы 1 - 4 подключенные к pcf8574
#  - !include flower/pump_pcf8574_2.yaml    # насосы 5 - 8 подключенные к pcf8574
  - !include flower/button_gpio.yaml       # кнопки 1 - 4 подключенные к GPIO
  - !include flower/ultrasonic.yaml        # сенсор уровня воды
  - !include flower/led.yaml               # светодиоды индикации состояний
#  - !include flower/button_pcf8574.yaml    # кнопки 1 - 4 подключенные к pcf8574
#  - !include flower/button_pcf8574_2.yaml  # кнопки 5 - 8 подключенные к pcf8574
#  - !include flower/led_pcf8574.yaml       # светодиоды индикации 1 - 8 подключенные к pcf8574






