substitutions:
  i2c_address_buttons: 0x21
  button_inverted: false

pcf8574:
  - id: pcf8574_buttons
    address: $i2c_address_buttons
    pcf8575: false

binary_sensor:
  - platform: gpio
    pin:
      pcf8574: pcf8574_buttons
      number: 0
      mode:
        input: true
      inverted: $button_inverted
    id: button1
    on_press:
      - lambda: |-
          if (id(button1_type_enable).state) {
            id(pump_on_zone_1).execute();
          } else {
            id(relay_1).toggle();
          }
  - platform: gpio
    pin:
      pcf8574: pcf8574_buttons
      number: 1
      mode:
        input: true
      inverted: $button_inverted
    id: button2
    on_press:
      - lambda: |-
          if (id(button2_type_enable).state) {
            id(pump_on_zone_2).execute();
          } else {
            id(relay_2).toggle();
          }
  - platform: gpio
    pin:
      pcf8574: pcf8574_buttons
      number: 2
      mode:
        input: true
      inverted: $button_inverted
    id: button3
    on_press:
      - lambda: |-
          if (id(button3_type_enable).state) {
            id(pump_on_zone_3).execute();
          } else {
            id(relay_3).toggle();
          }
  - platform: gpio
    pin:
      pcf8574: pcf8574_buttons
      number: 3
      mode:
        input: true
      inverted: $button_inverted
    id: button4
    on_press:
      - lambda: |-
          if (id(button4_type_enable).state) {
            id(pump_on_zone_4).execute();
          } else {
            id(relay_4).toggle();
          }
switch:
  - platform: template
    name: $button_type 1
    id: button1_type_enable
    icon: mdi:calendar-clock
    web_server:
      sorting_group_id: group21
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: template
    name: $button_type 2
    id: button2_type_enable
    icon: mdi:calendar-clock
    web_server:
      sorting_group_id: group22
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: template
    name: $button_type 3
    id: button3_type_enable
    icon: mdi:calendar-clock
    web_server:
      sorting_group_id: group23
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF

  - platform: template
    name: $button_type 4
    id: button4_type_enable
    icon: mdi:calendar-clock
    web_server:
      sorting_group_id: group24
    optimistic: true
    restore_mode: RESTORE_DEFAULT_OFF
