substitutions:
  max_value_time: 60
  relay1_pin: 0
  relay2_pin: 1
  relay3_pin: 2
  relay4_pin: 3
  i2c_adress1: 0x20
  relay_inverted: false

pcf8574:
  - id: pcf8574_hub
    address: $i2c_adress1
    pcf8575: false

globals:
  - id: last_watering_zone1
    type: std::string
    restore_value: true
    max_restore_data_length: 20
    initial_value: '"—"'
  - id: last_watering_zone2
    type: std::string
    restore_value: true
    max_restore_data_length: 20
    initial_value: '"—"'
  - id: last_watering_zone3
    type: std::string
    restore_value: true
    max_restore_data_length: 20
    initial_value: '"—"'
  - id: last_watering_zone4
    type: std::string
    restore_value: true
    max_restore_data_length: 20
    initial_value: '"—"'
  - id: relay1_state
    type: bool
    restore_value: true
    initial_value: "false"
  - id: relay2_state
    type: bool
    restore_value: true
    initial_value: "false"
  - id: relay3_state
    type: bool
    restore_value: true
    initial_value: "false"
  - id: relay4_state
    type: bool
    restore_value: true
    initial_value: "false"
  - id: pump_run_time_1
    type: int
    restore_value: yes
    initial_value: '10'
  - id: pump_run_time_2
    type: int
    restore_value: yes
    initial_value: '10'
  - id: pump_run_time_3
    type: int
    restore_value: yes
    initial_value: '10'
  - id: pump_run_time_4
    type: int
    restore_value: yes
    initial_value: '10'

script:
  - id: pump_on_zone_1
    then:
      - switch.turn_on: relay_1
      - delay: !lambda 'return id(pump_run_time_1) * 1000;'
      - switch.turn_off: relay_1
  - id: pump_on_zone_2
    then:
      - switch.turn_on: relay_2
      - delay: !lambda 'return id(pump_run_time_2) * 1000;'
      - switch.turn_off: relay_2
  - id: pump_on_zone_3
    then:
      - switch.turn_on: relay_3
      - delay: !lambda 'return id(pump_run_time_3) * 1000;'
      - switch.turn_off: relay_3
  - id: pump_on_zone_4
    then:
      - switch.turn_on: relay_4
      - delay: !lambda 'return id(pump_run_time_4) * 1000;'
      - switch.turn_off: relay_4

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          id(last_watering_sensor_1).publish_state(id(last_watering_zone1));
          id(last_watering_sensor_2).publish_state(id(last_watering_zone2));
          id(last_watering_sensor_3).publish_state(id(last_watering_zone3));
          id(last_watering_sensor_4).publish_state(id(last_watering_zone4));

          id(pump_time_slider_1).publish_state(id(pump_run_time_1));
          id(pump_time_slider_2).publish_state(id(pump_run_time_2));
          id(pump_time_slider_3).publish_state(id(pump_run_time_3));
          id(pump_time_slider_4).publish_state(id(pump_run_time_4));

switch:
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub
      number: ${relay1_pin}
      mode: OUTPUT
      inverted: $relay_inverted
    name: $pump 1
    id: relay_1
    icon: "mdi:pump"
    restore_mode: RESTORE_DEFAULT_OFF
    web_server:
      sorting_weight: 7
      sorting_group_id: group1
    on_turn_on:
      - lambda: |-
          id(last_watering_zone1) = id(sntp_time).now().strftime("%Y-%m-%d %H:%M");
          id(last_watering_sensor_1).publish_state(id(last_watering_zone1));
          id(relay1_state) = true;
    on_turn_off:
      - lambda: |-
          id(relay1_state) = false;

  - platform: gpio
    pin:
      pcf8574: pcf8574_hub
      number: ${relay2_pin}
      mode: OUTPUT
      inverted: $relay_inverted
    name: $pump 2
    id: relay_2
    icon: "mdi:pump"
    restore_mode: RESTORE_DEFAULT_OFF
    web_server:
      sorting_weight: 7
      sorting_group_id: group2
    on_turn_on:
      - lambda: |-
          id(last_watering_zone2) = id(sntp_time).now().strftime("%Y-%m-%d %H:%M");
          id(last_watering_sensor_2).publish_state(id(last_watering_zone2));
          id(relay2_state) = true;
    on_turn_off:
      - lambda: |-
          id(relay2_state) = false;


  - platform: gpio
    pin:
      pcf8574: pcf8574_hub
      number: ${relay3_pin}
      mode: OUTPUT
      inverted: $relay_inverted
    name: $pump 3
    id: relay_3
    icon: "mdi:pump"
    restore_mode: RESTORE_DEFAULT_OFF
    web_server:
      sorting_weight: 7
      sorting_group_id: group3
    on_turn_on:
      - lambda: |-
          id(last_watering_zone3) = id(sntp_time).now().strftime("%Y-%m-%d %H:%M");
          id(last_watering_sensor_3).publish_state(id(last_watering_zone3));
          id(relay3_state) = true;
    on_turn_off:
      - lambda: |-
          id(relay3_state) = false;


  - platform: gpio
    pin:
      pcf8574: pcf8574_hub
      number: ${relay4_pin}
      mode: OUTPUT
      inverted: $relay_inverted
    name: $pump 4
    id: relay_4
    icon: "mdi:pump"
    restore_mode: RESTORE_DEFAULT_OFF
    web_server:
      sorting_weight: 7
      sorting_group_id: group4
    on_turn_on:
      - lambda: |-
          id(last_watering_zone4) = id(sntp_time).now().strftime("%Y-%m-%d %H:%M");
          id(last_watering_sensor_4).publish_state(id(last_watering_zone4));
          id(relay4_state) = true;
    on_turn_off:
      - lambda: |-
          id(relay4_state) = false;


text_sensor:
  - platform: template
    name: $last_water 1
    id: last_watering_sensor_1
    icon: mdi:clock
    web_server:
      sorting_weight: 6
      sorting_group_id: group1
  - platform: template
    name: $last_water 2
    id: last_watering_sensor_2
    icon: mdi:clock
    web_server:
      sorting_weight: 6
      sorting_group_id: group2
  - platform: template
    name: $last_water 3
    id: last_watering_sensor_3
    icon: mdi:clock
    web_server:
      sorting_weight: 6
      sorting_group_id: group3
  - platform: template
    name: $last_water 4
    id: last_watering_sensor_4
    icon: mdi:clock
    web_server:
      sorting_weight: 6
      sorting_group_id: group4

number:
  - platform: template
    name: $pump_time 1
    id: pump_time_slider_1
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: $max_value_time
    step: 1
    unit_of_measurement: "s"
    icon: mdi:timer-outline
    web_server:
      sorting_group_id: group21
    set_action:
      - lambda: |-
          id(pump_run_time_1) = x;

  - platform: template
    name: $pump_time 2
    id: pump_time_slider_2
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: $max_value_time
    step: 1
    unit_of_measurement: "s"
    icon: mdi:timer-outline
    web_server:
      sorting_group_id: group22
    set_action:
      - lambda: |-
          id(pump_run_time_2) = x;

  - platform: template
    name: $pump_time 3
    id: pump_time_slider_3
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: $max_value_time
    step: 1
    unit_of_measurement: "s"
    icon: mdi:timer-outline
    web_server:
      sorting_group_id: group23
    set_action:
      - lambda: |-
          id(pump_run_time_3) = x;

  - platform: template
    name: $pump_time 4
    id: pump_time_slider_4
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: $max_value_time
    step: 1
    unit_of_measurement: "s"
    icon: mdi:timer-outline
    web_server:
      sorting_group_id: group24
    set_action:
      - lambda: |-
          id(pump_run_time_4) = x;

