substitutions:
  relay5_pin: 4
  relay6_pin: 5
  relay7_pin: 6
  relay8_pin: 7

globals:
  - id: last_watering_zone5
    type: std::string
    restore_value: true
    max_restore_data_length: 20
    initial_value: '"—"'
  - id: last_watering_zone6
    type: std::string
    restore_value: true
    max_restore_data_length: 20
    initial_value: '"—"'
  - id: last_watering_zone7
    type: std::string
    restore_value: true
    max_restore_data_length: 20
    initial_value: '"—"'
  - id: last_watering_zone8
    type: std::string
    restore_value: true
    max_restore_data_length: 20
    initial_value: '"—"'
  - id: relay5_state
    type: bool
    restore_value: true
    initial_value: "false"
  - id: relay6_state
    type: bool
    restore_value: true
    initial_value: "false"
  - id: relay7_state
    type: bool
    restore_value: true
    initial_value: "false"
  - id: relay8_state
    type: bool
    restore_value: true
    initial_value: "false"
  - id: pump_run_time_5
    type: int
    restore_value: yes
    initial_value: '10'
  - id: pump_run_time_6
    type: int
    restore_value: yes
    initial_value: '10'
  - id: pump_run_time_7
    type: int
    restore_value: yes
    initial_value: '10'
  - id: pump_run_time_8
    type: int
    restore_value: yes
    initial_value: '10'


script:
  - id: pump_on_zone_5
    then:
      - switch.turn_on: relay_5
      - delay: !lambda 'return id(pump_run_time_5) * 1000;'
      - switch.turn_off: relay_5
  - id: pump_on_zone_6
    then:
      - switch.turn_on: relay_6
      - delay: !lambda 'return id(pump_run_time_6) * 1000;'
      - switch.turn_off: relay_6
  - id: pump_on_zone_7
    then:
      - switch.turn_on: relay_7
      - delay: !lambda 'return id(pump_run_time_7) * 1000;'
      - switch.turn_off: relay_7
  - id: pump_on_zone_8
    then:
      - switch.turn_on: relay_8
      - delay: !lambda 'return id(pump_run_time_8) * 1000;'
      - switch.turn_off: relay_8

esphome:
  on_boot:
    priority: -100
    then:
      - lambda: |-
          id(last_watering_sensor_5).publish_state(id(last_watering_zone5));
          id(last_watering_sensor_6).publish_state(id(last_watering_zone6));
          id(last_watering_sensor_7).publish_state(id(last_watering_zone7));
          id(last_watering_sensor_8).publish_state(id(last_watering_zone8));

switch:
  - platform: gpio
    pin:
      pcf8574: pcf8574_hub
      number: ${relay5_pin}
      mode: OUTPUT
      inverted: $relay_inverted
    name: $pump 5
    id: relay_5
    icon: "mdi:pump"
    restore_mode: RESTORE_DEFAULT_OFF
    web_server:
      sorting_weight: 7
      sorting_group_id: group5
    on_turn_on:
      - lambda: |-
          id(last_watering_zone5) = id(sntp_time).now().strftime("%Y-%m-%d %H:%M");
          id(last_watering_sensor_5).publish_state(id(last_watering_zone5));
          id(relay5_state) = true;
    on_turn_off:
      - lambda: |-
          id(relay5_state) = false;

  - platform: gpio
    pin:
      pcf8574: pcf8574_hub
      number: ${relay6_pin}
      mode: OUTPUT
      inverted: $relay_inverted
    name: $pump 6
    id: relay_6
    icon: "mdi:pump"
    restore_mode: RESTORE_DEFAULT_OFF
    web_server:
      sorting_weight: 7
      sorting_group_id: group6
    on_turn_on:
      - lambda: |-
          id(last_watering_zone6) = id(sntp_time).now().strftime("%Y-%m-%d %H:%M");
          id(last_watering_sensor_6).publish_state(id(last_watering_zone6));
          id(relay6_state) = true;
    on_turn_off:
      - lambda: |-
          id(relay6_state) = false;


  - platform: gpio
    pin:
      pcf8574: pcf8574_hub
      number: ${relay7_pin}
      mode: OUTPUT
      inverted: $relay_inverted
    name: $pump 7
    id: relay_7
    icon: "mdi:pump"
    restore_mode: RESTORE_DEFAULT_OFF
    web_server:
      sorting_weight: 7
      sorting_group_id: group7
    on_turn_on:
      - lambda: |-
          id(last_watering_zone7) = id(sntp_time).now().strftime("%Y-%m-%d %H:%M");
          id(last_watering_sensor_7).publish_state(id(last_watering_zone7));
          id(relay7_state) = true;
    on_turn_off:
      - lambda: |-
          id(relay7_state) = false;


  - platform: gpio
    pin:
      pcf8574: pcf8574_hub
      number: ${relay8_pin}
      mode: OUTPUT
      inverted: $relay_inverted
    name: $pump 8
    id: relay_8
    icon: "mdi:pump"
    restore_mode: RESTORE_DEFAULT_OFF
    web_server:
      sorting_weight: 7
      sorting_group_id: group8
    on_turn_on:
      - lambda: |-
          id(last_watering_zone8) = id(sntp_time).now().strftime("%Y-%m-%d %H:%M");
          id(last_watering_sensor_8).publish_state(id(last_watering_zone8));
          id(relay8_state) = true;
    on_turn_off:
      - lambda: |-
          id(relay8_state) = false;


text_sensor:
  - platform: template
    name: $last_water 5
    id: last_watering_sensor_5
    icon: mdi:clock
    web_server:
      sorting_weight: 6
      sorting_group_id: group5
  - platform: template
    name: $last_water 6
    id: last_watering_sensor_6
    icon: mdi:clock
    web_server:
      sorting_weight: 6
      sorting_group_id: group6
  - platform: template
    name: $last_water 7
    id: last_watering_sensor_7
    icon: mdi:clock
    web_server:
      sorting_weight: 6
      sorting_group_id: group7
  - platform: template
    name: $last_water 8
    id: last_watering_sensor_8
    icon: mdi:clock
    web_server:
      sorting_weight: 6
      sorting_group_id: group8

number:
  - platform: template
    name: $pump_time 5
    id: pump_time_slider_5
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: $max_value_time
    step: 1
    unit_of_measurement: "s"
    icon: mdi:timer-outline
    web_server:
      sorting_group_id: group25
    set_action:
      - lambda: |-
          id(pump_run_time_5) = x;

  - platform: template
    name: $pump_time 6
    id: pump_time_slider_6
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: $max_value_time
    step: 1
    unit_of_measurement: "s"
    icon: mdi:timer-outline
    web_server:
      sorting_group_id: group26
    set_action:
      - lambda: |-
          id(pump_run_time_6) = x;

  - platform: template
    name: $pump_time 7
    id: pump_time_slider_7
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: $max_value_time
    step: 1
    unit_of_measurement: "s"
    icon: mdi:timer-outline
    web_server:
      sorting_group_id: group27
    set_action:
      - lambda: |-
          id(pump_run_time_7) = x;

  - platform: template
    name: $pump_time 8
    id: pump_time_slider_8
    optimistic: true
    restore_value: true
    min_value: 1
    max_value: $max_value_time
    step: 1
    unit_of_measurement: "s"
    icon: mdi:timer-outline
    web_server:
      sorting_group_id: group28
    set_action:
      - lambda: |-
          id(pump_run_time_8) = x;
